# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Python application33

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest numpy pandas scipy pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        mkdir test-results
        python -m pytest tests --cov=. --cov-report=xml:cov.xml --junitxml=test-results/junit.xml
        python -m pytest tests2 --cov=. --cov-report=xml:cov2.xml --junitxml=test-results/junit2.xml
    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
          name: test-result-python
          path: |
            /home/runner/work/pytest_tutorial/pytest_tutorial/test-results/
      
    - name: Archive coverage results
      uses: actions/upload-artifact@v2
      with:
          name: coverage-artifact
          path: |
            /home/runner/work/pytest_tutorial/pytest_tutorial/cov.xml
            /home/runner/work/pytest_tutorial/pytest_tutorial/cov2.xml
